# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6f1788c979f4cde2a39a3275c026d838"
application_url = "https://hence-inter-scoring-tribes.trycloudflare.com"
embedded = true
name = "catalog-ai"
handle = "catalog-ai-1"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://hence-inter-scoring-tribes.trycloudflare.com/auth/callback",
  "https://hence-inter-scoring-tribes.trycloudflare.com/auth/shopify/callback",
  "https://hence-inter-scoring-tribes.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "smart-lights-san-francisco.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
